### ISSUE TITLE
Can get average salary of respondents with "Not Listed" gender

### ISSUE THREAD

**Issue by pwim** [SachaG/tokyodev#62]
Even though there are only two of them.

**Comment by SachaG** [comment]
Oh I think that's because the way I've set up the cutoff, it hides data if there's less than 10 people in the overall dataset, which makes sense for simple filtering. But in this case since we're cross-referencing two variables we probably want to trigger the cutoff if there's fewer than 10 people in the *cross-section* instead.

**Comment by SachaG** [comment]
- [ ] Also apply same behavior for filters as for facets
- [ ] Make sure 0 answers are also treated the same way (or else actual answers can be isolated by elimination)
